// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YapıRuhsatOtomasyonu.Data;

#nullable disable

namespace YapıRuhsatOtomasyonu.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511174037_DosyaTipiDetaySayfasınaEklendi")]
    partial class DosyaTipiDetaySayfasınaEklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YapıRuhsatOtomasyonu.Models.BelgeDetayModel", b =>
                {
                    b.Property<int>("SiraNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiraNo"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BelgeAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BelgeYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BelgeyeEsasRuhsat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegistirenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegistirmeTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DigerBilgiler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsaatHarci")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IskanNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IskanTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IskanVerilisAmaci")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KayitTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Muteahhit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParselinAlani")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuhsatBilgileri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuhsatNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuhsatTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuhsatVerilisAmaci")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SantiyeSefi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YapiDenetimFirmasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YapiKimlikNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YapiSiraNo")
                        .HasColumnType("int");

                    b.HasKey("SiraNo");

                    b.HasIndex("YapiSiraNo");

                    b.ToTable("BelgeDetaylar");
                });

            modelBuilder.Entity("YapıRuhsatOtomasyonu.Models.BelgeTipiModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegistirenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegistirmeTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DigerBilgiler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KayitTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BelgeTipleri");
                });

            modelBuilder.Entity("YapıRuhsatOtomasyonu.Models.BirimModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirimAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegistirenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegistirmeTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DigerBilgiler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KayitTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Birimler");
                });

            modelBuilder.Entity("YapıRuhsatOtomasyonu.Models.DosyaDetayModel", b =>
                {
                    b.Property<int>("SiraNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiraNo"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegistirenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegistirmeTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DigerBilgiler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DosyaTipId")
                        .HasColumnType("int");

                    b.Property<string>("DosyaYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KayitTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YapiSiraNo")
                        .HasColumnType("int");

                    b.HasKey("SiraNo");

                    b.HasIndex("DosyaTipId");

                    b.ToTable("DosyaDetay");
                });

            modelBuilder.Entity("YapıRuhsatOtomasyonu.Models.DosyaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DosyaAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DosyaYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KayitTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uzanti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YapiSiraNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Dosyalar");
                });

            modelBuilder.Entity("YapıRuhsatOtomasyonu.Models.DosyaTipiModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegistirenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegistirmeTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DigerBilgiler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KayitTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DosyaTipleri");
                });

            modelBuilder.Entity("YapıRuhsatOtomasyonu.Models.IskanAmaciModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegistirenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegistirmeTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DigerBilgiler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KayitTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerilisAmaci")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IskanAmaclari");
                });

            modelBuilder.Entity("YapıRuhsatOtomasyonu.Models.KullaniciModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("AnneAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BabaAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Birim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegistirenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegistirmeTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DigerBilgiler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DogumTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DogumYeri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GsmNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KayitTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciBirimi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciTipi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tanim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcKimlikNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unvan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("YapıRuhsatOtomasyonu.Models.KullaniciTipiModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegistirenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegistirmeTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DigerBilgiler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KayitTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciTipi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KullaniciTipleri");
                });

            modelBuilder.Entity("YapıRuhsatOtomasyonu.Models.RuhsatAmaciModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegistirenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegistirmeTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DigerBilgiler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KayitTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerilisAmaci")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RuhsatAmaclari");
                });

            modelBuilder.Entity("YapıRuhsatOtomasyonu.Models.SicilModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlanKisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnneAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BabaAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BilirKisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BilmemNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegistirenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegistirmeTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DigerBilgiler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DogumTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DogumYeri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirmaAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KayitTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SicilTipi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcKimlikNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VergiDairesi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VergiNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Siciller");
                });

            modelBuilder.Entity("YapıRuhsatOtomasyonu.Models.SicilTipiModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegistirenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegistirmeTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DigerBilgiler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KayitTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SicilTipi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SicilTipleri");
                });

            modelBuilder.Entity("YapıRuhsatOtomasyonu.Models.UnvanModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegistirenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegistirmeTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DigerBilgiler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KayitTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnvanAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Unvanlar");
                });

            modelBuilder.Entity("YapıRuhsatOtomasyonu.Models.YapiModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cadde")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegistirenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegistirmeTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DigerBilgiler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KayitTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mahalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parsel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sokak")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YapiKimlikNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YapiSahibi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Yapilar");
                });

            modelBuilder.Entity("YapıRuhsatOtomasyonu.Models.YetkiModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DegistirenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegistirmeTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EkleYetki")
                        .HasColumnType("bit");

                    b.Property<bool>("GuncelleYetki")
                        .HasColumnType("bit");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KayitTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modul")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Panel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SilYetki")
                        .HasColumnType("bit");

                    b.Property<bool>("YetkiVerildiMi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Yetkiler");
                });

            modelBuilder.Entity("YapıRuhsatOtomasyonu.Models.BelgeDetayModel", b =>
                {
                    b.HasOne("YapıRuhsatOtomasyonu.Models.YapiModel", "Yapi")
                        .WithMany()
                        .HasForeignKey("YapiSiraNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Yapi");
                });

            modelBuilder.Entity("YapıRuhsatOtomasyonu.Models.DosyaDetayModel", b =>
                {
                    b.HasOne("YapıRuhsatOtomasyonu.Models.DosyaTipiModel", "DosyaTipi")
                        .WithMany()
                        .HasForeignKey("DosyaTipId");

                    b.Navigation("DosyaTipi");
                });
#pragma warning restore 612, 618
        }
    }
}
